//Jmol Version 10.9.74  2006-10-09 21:20
addMenuItem('	.popupMenu.-	-		')
addMenuItem('	.popupMenu.selectMenu.showSelectionsCheckbox	Selection Halos	set showSelections [true|false]	')
addMenuItem('	.popupMenu.selectMenu.-	-		')
addMenuItem('	.popupMenu.selectMenu.selectAll	All	select all	')
addMenuItem('	.popupMenu.selectMenu.selectNone	None	select none	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.selectMenu.-	-		')
addMenuItem('	.popupMenu.selectMenu.PDBproteinMenu.allProtein	All	select protein	')
addMenuItem('	.popupMenu.selectMenu.PDBproteinMenu.proteinBackbone	Backbone	select protein and backbone	')
addMenuItem('	.popupMenu.selectMenu.PDBproteinMenu.proteinSideChains	Side Chains	select protein and not backbone	')
addMenuItem('	.popupMenu.selectMenu.PDBproteinMenu.-	-		')
addMenuItem('	.popupMenu.selectMenu.PDBproteinMenu.polar	Polar Residues	select protein and polar	')
addMenuItem('	.popupMenu.selectMenu.PDBproteinMenu.nonpolar	Nonpolar Residues	select protein and not polar	')
addMenuItem('	.popupMenu.selectMenu.PDBproteinMenu.-	-		')
addMenuItem('	.popupMenu.selectMenu.PDBproteinMenu.positiveCharge	Basic Residues (+)	select protein and basic	')
addMenuItem('	.popupMenu.selectMenu.PDBproteinMenu.negativeCharge	Acidic Residues (-)	select protein and acidic	')
addMenuItem('	.popupMenu.selectMenu.PDBproteinMenu.noCharge	Uncharged Residues	select protein and not (acidic,basic)	')
addMenuItem('	.popupMenu.selectMenu.PDBproteinMenu.-	-		')
addMenuItem('	----	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.selectMenu.PDBnucleicMenu.allNucleic	All	select nucleic	')
addMenuItem('	.popupMenu.selectMenu.PDBnucleicMenu.nucleicBackbone	Backbone	select nucleic and backbone	')
addMenuItem('	.popupMenu.selectMenu.PDBnucleicMenu.nucleicBases	Bases	select nucleic and not backbone	')
addMenuItem('	.popupMenu.selectMenu.PDBnucleicMenu.-	-		')
addMenuItem('	.popupMenu.selectMenu.PDBnucleicMenu.DNA	DNA	select dna	')
addMenuItem('	.popupMenu.selectMenu.PDBnucleicMenu.RNA	RNA	select rna	')
addMenuItem('	.popupMenu.selectMenu.PDBnucleicMenu.-	-		')
addMenuItem('	.popupMenu.selectMenu.PDBnucleicMenu.A	A	select a	')
addMenuItem('	.popupMenu.selectMenu.PDBnucleicMenu.C	C	select c	')
addMenuItem('	.popupMenu.selectMenu.PDBnucleicMenu.G	G	select g	')
addMenuItem('	.popupMenu.selectMenu.PDBnucleicMenu.T	T	select t	')
addMenuItem('	.popupMenu.selectMenu.PDBnucleicMenu.U	U	select u	')
addMenuItem('	.popupMenu.selectMenu.PDBnucleicMenu.-	-		')
addMenuItem('	.popupMenu.selectMenu.PDBnucleicMenu.atPairs	AT pairs	select a,t	')
addMenuItem('	.popupMenu.selectMenu.PDBnucleicMenu.auPairs	AU pairs	select a,u	')
addMenuItem('	.popupMenu.selectMenu.PDBnucleicMenu.gcPairs	GC pairs	select g,c	')
addMenuItem('	----	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.selectMenu.PDBheteroMenu.-	-		')
addMenuItem('	.popupMenu.selectMenu.PDBheteroMenu.allHetero	All PDB "HETATM"	select hetero	')
addMenuItem('	.popupMenu.selectMenu.PDBheteroMenu.Solvent	All Solvent	select solvent	')
addMenuItem('	.popupMenu.selectMenu.PDBheteroMenu.Water	All Water	select water	')
addMenuItem('	.popupMenu.selectMenu.PDBheteroMenu.-	-		')
addMenuItem('	.popupMenu.selectMenu.PDBheteroMenu.Ligand	Ligand (hetero and not solvent)	select ligand	')
addMenuItem('	.popupMenu.selectMenu.PDBheteroMenu.exceptWater	Nonaqueous HETATM (hetero and not water)	select hetero and not water	')
addMenuItem('	.popupMenu.selectMenu.PDBheteroMenu.nonWaterSolvent	Nonaqueous Solvent (solvent and not water)	select solvent and not water	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.selectMenu.PDBcarbohydrate	Carbohydrate	select carbohydrate	')
addMenuItem('	.popupMenu.selectMenu.PDBnoneOfTheAbove	None of the above	select not(hetero,protein,nucleic,carbohydrate)	')
addMenuItem('	.popupMenu.selectMenu.-	-		')
addMenuItem('	.popupMenu.selectMenu.invertSelection	Invert Selection	select not selected	')
addMenuItem('	.popupMenu.selectMenu.restrictToSelection	Display Selected Only	select selected; restrict selected	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.colorMenu.colorrasmolCheckbox	RasMol Colors	set colorrasmol [true|false]	')
addMenuItem('	.popupMenu.colorMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorAtomsMenu.SchemeMenu.cpk	Element (CPK)	color Atoms cpk	')
addMenuItem('	.popupMenu.colorMenu.colorAtomsMenu.SchemeMenu.amino	Amino	color Atoms amino	')
addMenuItem('	.popupMenu.colorMenu.colorAtomsMenu.SchemeMenu.structure	Secondary Structure	color Atoms structure	')
addMenuItem('	.popupMenu.colorMenu.colorAtomsMenu.SchemeMenu.chain	Chain	color Atoms chain	')
addMenuItem('	.popupMenu.colorMenu.colorAtomsMenu.SchemeMenu.formalcharge	Formal Charge	color Atoms formalcharge	')
addMenuItem('	.popupMenu.colorMenu.colorAtomsMenu.SchemeMenu.partialcharge	Partial Charge	color Atoms partialcharge	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.colorMenu.colorAtomsMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorAtomsMenu.black	Black	color Atoms black	')
addMenuItem('	.popupMenu.colorMenu.colorAtomsMenu.white	White	color Atoms white	')
addMenuItem('	.popupMenu.colorMenu.colorAtomsMenu.red	Red	color Atoms red	')
addMenuItem('	.popupMenu.colorMenu.colorAtomsMenu.orange	Orange	color Atoms orange	')
addMenuItem('	.popupMenu.colorMenu.colorAtomsMenu.yellow	Yellow	color Atoms yellow	')
addMenuItem('	.popupMenu.colorMenu.colorAtomsMenu.green	Green	color Atoms green	')
addMenuItem('	.popupMenu.colorMenu.colorAtomsMenu.cyan	Cyan	color Atoms cyan	')
addMenuItem('	.popupMenu.colorMenu.colorAtomsMenu.blue	Blue	color Atoms blue	')
addMenuItem('	.popupMenu.colorMenu.colorAtomsMenu.indigo	Indigo	color Atoms indigo	')
addMenuItem('	.popupMenu.colorMenu.colorAtomsMenu.violet	Violet	color Atoms violet	')
addMenuItem('	.popupMenu.colorMenu.colorAtomsMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorAtomsMenu.opaque	Make Opaque	color Atoms opaque	')
addMenuItem('	.popupMenu.colorMenu.colorAtomsMenu.translucent	Make Translucent	color Atoms translucent	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.colorMenu.colorBondsMenu.none	Inherit	color Bonds none	')
addMenuItem('	.popupMenu.colorMenu.colorBondsMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorBondsMenu.black	Black	color Bonds black	')
addMenuItem('	.popupMenu.colorMenu.colorBondsMenu.white	White	color Bonds white	')
addMenuItem('	.popupMenu.colorMenu.colorBondsMenu.red	Red	color Bonds red	')
addMenuItem('	.popupMenu.colorMenu.colorBondsMenu.orange	Orange	color Bonds orange	')
addMenuItem('	.popupMenu.colorMenu.colorBondsMenu.yellow	Yellow	color Bonds yellow	')
addMenuItem('	.popupMenu.colorMenu.colorBondsMenu.green	Green	color Bonds green	')
addMenuItem('	.popupMenu.colorMenu.colorBondsMenu.cyan	Cyan	color Bonds cyan	')
addMenuItem('	.popupMenu.colorMenu.colorBondsMenu.blue	Blue	color Bonds blue	')
addMenuItem('	.popupMenu.colorMenu.colorBondsMenu.indigo	Indigo	color Bonds indigo	')
addMenuItem('	.popupMenu.colorMenu.colorBondsMenu.violet	Violet	color Bonds violet	')
addMenuItem('	.popupMenu.colorMenu.colorBondsMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorBondsMenu.opaque	Make Opaque	color Bonds opaque	')
addMenuItem('	.popupMenu.colorMenu.colorBondsMenu.translucent	Make Translucent	color Bonds translucent	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.colorMenu.colorHbondsMenu.none	Inherit	color Hbonds none	')
addMenuItem('	.popupMenu.colorMenu.colorHbondsMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorHbondsMenu.black	Black	color Hbonds black	')
addMenuItem('	.popupMenu.colorMenu.colorHbondsMenu.white	White	color Hbonds white	')
addMenuItem('	.popupMenu.colorMenu.colorHbondsMenu.red	Red	color Hbonds red	')
addMenuItem('	.popupMenu.colorMenu.colorHbondsMenu.orange	Orange	color Hbonds orange	')
addMenuItem('	.popupMenu.colorMenu.colorHbondsMenu.yellow	Yellow	color Hbonds yellow	')
addMenuItem('	.popupMenu.colorMenu.colorHbondsMenu.green	Green	color Hbonds green	')
addMenuItem('	.popupMenu.colorMenu.colorHbondsMenu.cyan	Cyan	color Hbonds cyan	')
addMenuItem('	.popupMenu.colorMenu.colorHbondsMenu.blue	Blue	color Hbonds blue	')
addMenuItem('	.popupMenu.colorMenu.colorHbondsMenu.indigo	Indigo	color Hbonds indigo	')
addMenuItem('	.popupMenu.colorMenu.colorHbondsMenu.violet	Violet	color Hbonds violet	')
addMenuItem('	.popupMenu.colorMenu.colorHbondsMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorHbondsMenu.opaque	Make Opaque	color Hbonds opaque	')
addMenuItem('	.popupMenu.colorMenu.colorHbondsMenu.translucent	Make Translucent	color Hbonds translucent	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.colorMenu.colorSSbondsMenu.none	Inherit	color SSbonds none	')
addMenuItem('	.popupMenu.colorMenu.colorSSbondsMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorSSbondsMenu.black	Black	color SSbonds black	')
addMenuItem('	.popupMenu.colorMenu.colorSSbondsMenu.white	White	color SSbonds white	')
addMenuItem('	.popupMenu.colorMenu.colorSSbondsMenu.red	Red	color SSbonds red	')
addMenuItem('	.popupMenu.colorMenu.colorSSbondsMenu.orange	Orange	color SSbonds orange	')
addMenuItem('	.popupMenu.colorMenu.colorSSbondsMenu.yellow	Yellow	color SSbonds yellow	')
addMenuItem('	.popupMenu.colorMenu.colorSSbondsMenu.green	Green	color SSbonds green	')
addMenuItem('	.popupMenu.colorMenu.colorSSbondsMenu.cyan	Cyan	color SSbonds cyan	')
addMenuItem('	.popupMenu.colorMenu.colorSSbondsMenu.blue	Blue	color SSbonds blue	')
addMenuItem('	.popupMenu.colorMenu.colorSSbondsMenu.indigo	Indigo	color SSbonds indigo	')
addMenuItem('	.popupMenu.colorMenu.colorSSbondsMenu.violet	Violet	color SSbonds violet	')
addMenuItem('	.popupMenu.colorMenu.colorSSbondsMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorSSbondsMenu.opaque	Make Opaque	color SSbonds opaque	')
addMenuItem('	.popupMenu.colorMenu.colorSSbondsMenu.translucent	Make Translucent	color SSbonds translucent	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorBackboneMenu.none	Inherit	color Backbone none	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorBackboneMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorBackboneMenu.SchemeMenu.cpk	Element (CPK)	color Backbone cpk	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorBackboneMenu.SchemeMenu.amino	Amino	color Backbone amino	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorBackboneMenu.SchemeMenu.structure	Secondary Structure	color Backbone structure	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorBackboneMenu.SchemeMenu.chain	Chain	color Backbone chain	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorBackboneMenu.SchemeMenu.formalcharge	Formal Charge	color Backbone formalcharge	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorBackboneMenu.SchemeMenu.partialcharge	Partial Charge	color Backbone partialcharge	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorBackboneMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorBackboneMenu.black	Black	color Backbone black	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorBackboneMenu.white	White	color Backbone white	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorBackboneMenu.red	Red	color Backbone red	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorBackboneMenu.orange	Orange	color Backbone orange	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorBackboneMenu.yellow	Yellow	color Backbone yellow	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorBackboneMenu.green	Green	color Backbone green	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorBackboneMenu.cyan	Cyan	color Backbone cyan	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorBackboneMenu.blue	Blue	color Backbone blue	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorBackboneMenu.indigo	Indigo	color Backbone indigo	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorBackboneMenu.violet	Violet	color Backbone violet	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorBackboneMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorBackboneMenu.opaque	Make Opaque	color Backbone opaque	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorBackboneMenu.translucent	Make Translucent	color Backbone translucent	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorCartoonsMenu.none	Inherit	color Cartoons none	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorCartoonsMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorCartoonsMenu.SchemeMenu.cpk	Element (CPK)	color Cartoons cpk	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorCartoonsMenu.SchemeMenu.amino	Amino	color Cartoons amino	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorCartoonsMenu.SchemeMenu.structure	Secondary Structure	color Cartoons structure	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorCartoonsMenu.SchemeMenu.chain	Chain	color Cartoons chain	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorCartoonsMenu.SchemeMenu.formalcharge	Formal Charge	color Cartoons formalcharge	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorCartoonsMenu.SchemeMenu.partialcharge	Partial Charge	color Cartoons partialcharge	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorCartoonsMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorCartoonsMenu.black	Black	color Cartoons black	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorCartoonsMenu.white	White	color Cartoons white	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorCartoonsMenu.red	Red	color Cartoons red	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorCartoonsMenu.orange	Orange	color Cartoons orange	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorCartoonsMenu.yellow	Yellow	color Cartoons yellow	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorCartoonsMenu.green	Green	color Cartoons green	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorCartoonsMenu.cyan	Cyan	color Cartoons cyan	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorCartoonsMenu.blue	Blue	color Cartoons blue	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorCartoonsMenu.indigo	Indigo	color Cartoons indigo	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorCartoonsMenu.violet	Violet	color Cartoons violet	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorCartoonsMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorCartoonsMenu.opaque	Make Opaque	color Cartoons opaque	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorCartoonsMenu.translucent	Make Translucent	color Cartoons translucent	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRibbonsMenu.none	Inherit	color Ribbons none	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRibbonsMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRibbonsMenu.SchemeMenu.cpk	Element (CPK)	color Ribbons cpk	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRibbonsMenu.SchemeMenu.amino	Amino	color Ribbons amino	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRibbonsMenu.SchemeMenu.structure	Secondary Structure	color Ribbons structure	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRibbonsMenu.SchemeMenu.chain	Chain	color Ribbons chain	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRibbonsMenu.SchemeMenu.formalcharge	Formal Charge	color Ribbons formalcharge	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRibbonsMenu.SchemeMenu.partialcharge	Partial Charge	color Ribbons partialcharge	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRibbonsMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRibbonsMenu.black	Black	color Ribbons black	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRibbonsMenu.white	White	color Ribbons white	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRibbonsMenu.red	Red	color Ribbons red	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRibbonsMenu.orange	Orange	color Ribbons orange	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRibbonsMenu.yellow	Yellow	color Ribbons yellow	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRibbonsMenu.green	Green	color Ribbons green	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRibbonsMenu.cyan	Cyan	color Ribbons cyan	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRibbonsMenu.blue	Blue	color Ribbons blue	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRibbonsMenu.indigo	Indigo	color Ribbons indigo	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRibbonsMenu.violet	Violet	color Ribbons violet	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRibbonsMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRibbonsMenu.opaque	Make Opaque	color Ribbons opaque	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRibbonsMenu.translucent	Make Translucent	color Ribbons translucent	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRocketsMenu.none	Inherit	color Rockets none	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRocketsMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRocketsMenu.SchemeMenu.cpk	Element (CPK)	color Rockets cpk	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRocketsMenu.SchemeMenu.amino	Amino	color Rockets amino	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRocketsMenu.SchemeMenu.structure	Secondary Structure	color Rockets structure	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRocketsMenu.SchemeMenu.chain	Chain	color Rockets chain	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRocketsMenu.SchemeMenu.formalcharge	Formal Charge	color Rockets formalcharge	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRocketsMenu.SchemeMenu.partialcharge	Partial Charge	color Rockets partialcharge	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRocketsMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRocketsMenu.black	Black	color Rockets black	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRocketsMenu.white	White	color Rockets white	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRocketsMenu.red	Red	color Rockets red	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRocketsMenu.orange	Orange	color Rockets orange	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRocketsMenu.yellow	Yellow	color Rockets yellow	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRocketsMenu.green	Green	color Rockets green	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRocketsMenu.cyan	Cyan	color Rockets cyan	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRocketsMenu.blue	Blue	color Rockets blue	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRocketsMenu.indigo	Indigo	color Rockets indigo	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRocketsMenu.violet	Violet	color Rockets violet	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRocketsMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRocketsMenu.opaque	Make Opaque	color Rockets opaque	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorRocketsMenu.translucent	Make Translucent	color Rockets translucent	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorStrandsMenu.none	Inherit	color Strands none	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorStrandsMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorStrandsMenu.SchemeMenu.cpk	Element (CPK)	color Strands cpk	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorStrandsMenu.SchemeMenu.amino	Amino	color Strands amino	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorStrandsMenu.SchemeMenu.structure	Secondary Structure	color Strands structure	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorStrandsMenu.SchemeMenu.chain	Chain	color Strands chain	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorStrandsMenu.SchemeMenu.formalcharge	Formal Charge	color Strands formalcharge	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorStrandsMenu.SchemeMenu.partialcharge	Partial Charge	color Strands partialcharge	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorStrandsMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorStrandsMenu.black	Black	color Strands black	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorStrandsMenu.white	White	color Strands white	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorStrandsMenu.red	Red	color Strands red	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorStrandsMenu.orange	Orange	color Strands orange	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorStrandsMenu.yellow	Yellow	color Strands yellow	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorStrandsMenu.green	Green	color Strands green	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorStrandsMenu.cyan	Cyan	color Strands cyan	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorStrandsMenu.blue	Blue	color Strands blue	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorStrandsMenu.indigo	Indigo	color Strands indigo	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorStrandsMenu.violet	Violet	color Strands violet	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorStrandsMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorStrandsMenu.opaque	Make Opaque	color Strands opaque	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorStrandsMenu.translucent	Make Translucent	color Strands translucent	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorTraceMenu.none	Inherit	color Trace none	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorTraceMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorTraceMenu.SchemeMenu.cpk	Element (CPK)	color Trace cpk	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorTraceMenu.SchemeMenu.amino	Amino	color Trace amino	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorTraceMenu.SchemeMenu.structure	Secondary Structure	color Trace structure	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorTraceMenu.SchemeMenu.chain	Chain	color Trace chain	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorTraceMenu.SchemeMenu.formalcharge	Formal Charge	color Trace formalcharge	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorTraceMenu.SchemeMenu.partialcharge	Partial Charge	color Trace partialcharge	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorTraceMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorTraceMenu.black	Black	color Trace black	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorTraceMenu.white	White	color Trace white	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorTraceMenu.red	Red	color Trace red	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorTraceMenu.orange	Orange	color Trace orange	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorTraceMenu.yellow	Yellow	color Trace yellow	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorTraceMenu.green	Green	color Trace green	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorTraceMenu.cyan	Cyan	color Trace cyan	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorTraceMenu.blue	Blue	color Trace blue	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorTraceMenu.indigo	Indigo	color Trace indigo	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorTraceMenu.violet	Violet	color Trace violet	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorTraceMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorTraceMenu.opaque	Make Opaque	color Trace opaque	')
addMenuItem('	.popupMenu.colorMenu.colorPDBstructuresMenu.colorTraceMenu.translucent	Make Translucent	color Trace translucent	')
addMenuItem('	----	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.colorMenu.colorIsoSurfaceMenu.black	Black	color IsoSurface black	')
addMenuItem('	.popupMenu.colorMenu.colorIsoSurfaceMenu.white	White	color IsoSurface white	')
addMenuItem('	.popupMenu.colorMenu.colorIsoSurfaceMenu.red	Red	color IsoSurface red	')
addMenuItem('	.popupMenu.colorMenu.colorIsoSurfaceMenu.orange	Orange	color IsoSurface orange	')
addMenuItem('	.popupMenu.colorMenu.colorIsoSurfaceMenu.yellow	Yellow	color IsoSurface yellow	')
addMenuItem('	.popupMenu.colorMenu.colorIsoSurfaceMenu.green	Green	color IsoSurface green	')
addMenuItem('	.popupMenu.colorMenu.colorIsoSurfaceMenu.cyan	Cyan	color IsoSurface cyan	')
addMenuItem('	.popupMenu.colorMenu.colorIsoSurfaceMenu.blue	Blue	color IsoSurface blue	')
addMenuItem('	.popupMenu.colorMenu.colorIsoSurfaceMenu.indigo	Indigo	color IsoSurface indigo	')
addMenuItem('	.popupMenu.colorMenu.colorIsoSurfaceMenu.violet	Violet	color IsoSurface violet	')
addMenuItem('	.popupMenu.colorMenu.colorIsoSurfaceMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorIsoSurfaceMenu.opaque	Make Opaque	color IsoSurface opaque	')
addMenuItem('	.popupMenu.colorMenu.colorIsoSurfaceMenu.translucent	Make Translucent	color IsoSurface translucent	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.colorMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorLabelsMenu.none	Inherit	color Labels none	')
addMenuItem('	.popupMenu.colorMenu.colorLabelsMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorLabelsMenu.black	Black	color Labels black	')
addMenuItem('	.popupMenu.colorMenu.colorLabelsMenu.white	White	color Labels white	')
addMenuItem('	.popupMenu.colorMenu.colorLabelsMenu.red	Red	color Labels red	')
addMenuItem('	.popupMenu.colorMenu.colorLabelsMenu.orange	Orange	color Labels orange	')
addMenuItem('	.popupMenu.colorMenu.colorLabelsMenu.yellow	Yellow	color Labels yellow	')
addMenuItem('	.popupMenu.colorMenu.colorLabelsMenu.green	Green	color Labels green	')
addMenuItem('	.popupMenu.colorMenu.colorLabelsMenu.cyan	Cyan	color Labels cyan	')
addMenuItem('	.popupMenu.colorMenu.colorLabelsMenu.blue	Blue	color Labels blue	')
addMenuItem('	.popupMenu.colorMenu.colorLabelsMenu.indigo	Indigo	color Labels indigo	')
addMenuItem('	.popupMenu.colorMenu.colorLabelsMenu.violet	Violet	color Labels violet	')
addMenuItem('	.popupMenu.colorMenu.colorLabelsMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorLabelsMenu.opaque	Make Opaque	color Labels opaque	')
addMenuItem('	.popupMenu.colorMenu.colorLabelsMenu.translucent	Make Translucent	color Labels translucent	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.colorMenu.colorVectorsMenu.none	Inherit	color Vectors none	')
addMenuItem('	.popupMenu.colorMenu.colorVectorsMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorVectorsMenu.black	Black	color Vectors black	')
addMenuItem('	.popupMenu.colorMenu.colorVectorsMenu.white	White	color Vectors white	')
addMenuItem('	.popupMenu.colorMenu.colorVectorsMenu.red	Red	color Vectors red	')
addMenuItem('	.popupMenu.colorMenu.colorVectorsMenu.orange	Orange	color Vectors orange	')
addMenuItem('	.popupMenu.colorMenu.colorVectorsMenu.yellow	Yellow	color Vectors yellow	')
addMenuItem('	.popupMenu.colorMenu.colorVectorsMenu.green	Green	color Vectors green	')
addMenuItem('	.popupMenu.colorMenu.colorVectorsMenu.cyan	Cyan	color Vectors cyan	')
addMenuItem('	.popupMenu.colorMenu.colorVectorsMenu.blue	Blue	color Vectors blue	')
addMenuItem('	.popupMenu.colorMenu.colorVectorsMenu.indigo	Indigo	color Vectors indigo	')
addMenuItem('	.popupMenu.colorMenu.colorVectorsMenu.violet	Violet	color Vectors violet	')
addMenuItem('	.popupMenu.colorMenu.colorVectorsMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorVectorsMenu.opaque	Make Opaque	color Vectors opaque	')
addMenuItem('	.popupMenu.colorMenu.colorVectorsMenu.translucent	Make Translucent	color Vectors translucent	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.colorMenu.-	-		')
addMenuItem('	.popupMenu.colorMenu.colorAxesMenu.gray	Gray	color Axes gray	')
addMenuItem('	.popupMenu.colorMenu.colorAxesMenu.salmon	Salmon	color Axes salmon	')
addMenuItem('	.popupMenu.colorMenu.colorAxesMenu.maroon	Maroon	color Axes maroon	')
addMenuItem('	.popupMenu.colorMenu.colorAxesMenu.olive	Olive	color Axes olive	')
addMenuItem('	.popupMenu.colorMenu.colorAxesMenu.slateblue	Slate Blue	color Axes slateblue	')
addMenuItem('	.popupMenu.colorMenu.colorAxesMenu.gold	Gold	color Axes gold	')
addMenuItem('	.popupMenu.colorMenu.colorAxesMenu.orchid	Orchid	color Axes orchid	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.colorMenu.colorBoundBoxMenu.gray	Gray	color BoundBox gray	')
addMenuItem('	.popupMenu.colorMenu.colorBoundBoxMenu.salmon	Salmon	color BoundBox salmon	')
addMenuItem('	.popupMenu.colorMenu.colorBoundBoxMenu.maroon	Maroon	color BoundBox maroon	')
addMenuItem('	.popupMenu.colorMenu.colorBoundBoxMenu.olive	Olive	color BoundBox olive	')
addMenuItem('	.popupMenu.colorMenu.colorBoundBoxMenu.slateblue	Slate Blue	color BoundBox slateblue	')
addMenuItem('	.popupMenu.colorMenu.colorBoundBoxMenu.gold	Gold	color BoundBox gold	')
addMenuItem('	.popupMenu.colorMenu.colorBoundBoxMenu.orchid	Orchid	color BoundBox orchid	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.colorMenu.colorUnitCellMenu.gray	Gray	color UnitCell gray	')
addMenuItem('	.popupMenu.colorMenu.colorUnitCellMenu.salmon	Salmon	color UnitCell salmon	')
addMenuItem('	.popupMenu.colorMenu.colorUnitCellMenu.maroon	Maroon	color UnitCell maroon	')
addMenuItem('	.popupMenu.colorMenu.colorUnitCellMenu.olive	Olive	color UnitCell olive	')
addMenuItem('	.popupMenu.colorMenu.colorUnitCellMenu.slateblue	Slate Blue	color UnitCell slateblue	')
addMenuItem('	.popupMenu.colorMenu.colorUnitCellMenu.gold	Gold	color UnitCell gold	')
addMenuItem('	.popupMenu.colorMenu.colorUnitCellMenu.orchid	Orchid	color UnitCell orchid	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.colorMenu.colorBackgroundMenu.black	Black	color Background black	')
addMenuItem('	.popupMenu.colorMenu.colorBackgroundMenu.white	White	color Background white	')
addMenuItem('	.popupMenu.colorMenu.colorBackgroundMenu.red	Red	color Background red	')
addMenuItem('	.popupMenu.colorMenu.colorBackgroundMenu.orange	Orange	color Background orange	')
addMenuItem('	.popupMenu.colorMenu.colorBackgroundMenu.yellow	Yellow	color Background yellow	')
addMenuItem('	.popupMenu.colorMenu.colorBackgroundMenu.green	Green	color Background green	')
addMenuItem('	.popupMenu.colorMenu.colorBackgroundMenu.cyan	Cyan	color Background cyan	')
addMenuItem('	.popupMenu.colorMenu.colorBackgroundMenu.blue	Blue	color Background blue	')
addMenuItem('	.popupMenu.colorMenu.colorBackgroundMenu.indigo	Indigo	color Background indigo	')
addMenuItem('	.popupMenu.colorMenu.colorBackgroundMenu.violet	Violet	color Background violet	')
addMenuItem('	----	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.renderMenu.perspectiveDepthCheckbox	Perspective Depth	set perspectiveDepth [true|false]	')
addMenuItem('	.popupMenu.renderMenu.stereoMenu.stereoNone	None	stereo off	')
addMenuItem('	.popupMenu.renderMenu.stereoMenu.stereoRedCyan	Red+Cyan glasses	stereo redcyan 3	')
addMenuItem('	.popupMenu.renderMenu.stereoMenu.stereoRedBlue	Red+Blue glasses	stereo redblue 3	')
addMenuItem('	.popupMenu.renderMenu.stereoMenu.stereoRedGreen	Red+Green glasses	stereo redgreen 3	')
addMenuItem('	.popupMenu.renderMenu.stereoMenu.stereoCrossEyed	Cross-eyed viewing	stereo 5	')
addMenuItem('	.popupMenu.renderMenu.stereoMenu.stereoWallEyed	Wall-eyed viewing	stereo -5	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.renderMenu.-	-		')
addMenuItem('	.popupMenu.renderMenu.renderSchemeMenu.renderCpkSpacefill	CPK Spacefill	backbone off;wireframe off;spacefill 100%	')
addMenuItem('	.popupMenu.renderMenu.renderSchemeMenu.renderBallAndStick	Ball and Stick	backbone off;spacefill 20%;wireframe 0.15	')
addMenuItem('	.popupMenu.renderMenu.renderSchemeMenu.renderSticks	Sticks	backbone off;spacefill off;wireframe 0.3	')
addMenuItem('	.popupMenu.renderMenu.renderSchemeMenu.renderWireframe	Wireframe	backbone off;spacefill off;wireframe on	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.renderMenu.-	-		')
addMenuItem('	.popupMenu.renderMenu.atomMenu.showHydrogensCheckbox	Show Hydrogens	set showHydrogens [true|false]	')
addMenuItem('	.popupMenu.renderMenu.atomMenu.-	-		')
addMenuItem('	.popupMenu.renderMenu.atomMenu.atomNone	Off	cpk off	')
addMenuItem('	.popupMenu.renderMenu.atomMenu.-	-		')
addMenuItem('	.popupMenu.renderMenu.atomMenu.atom15	15% van der Waals	cpk 15%	')
addMenuItem('	.popupMenu.renderMenu.atomMenu.atom20	20% van der Waals	cpk 20%	')
addMenuItem('	.popupMenu.renderMenu.atomMenu.atom25	25% van der Waals	cpk 25%	')
addMenuItem('	.popupMenu.renderMenu.atomMenu.atom50	50% van der Waals	cpk 50%	')
addMenuItem('	.popupMenu.renderMenu.atomMenu.atom75	75% van der Waals	cpk 75%	')
addMenuItem('	.popupMenu.renderMenu.atomMenu.atom100	100% van der Waals	cpk on	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.renderMenu.labelMenu.labelNone	None	label off	')
addMenuItem('	.popupMenu.renderMenu.labelMenu.-	-		')
addMenuItem('	.popupMenu.renderMenu.labelMenu.labelSymbol	With Element Symbol	label %e	')
addMenuItem('	.popupMenu.renderMenu.labelMenu.labelName	With Atom Name	label %a	')
addMenuItem('	.popupMenu.renderMenu.labelMenu.labelNumber	With Atom Number	label %i	')
addMenuItem('	.popupMenu.renderMenu.labelMenu.-	-		')
addMenuItem('	.popupMenu.renderMenu.labelMenu.labelPositionMenu.labelCentered	Centered	set labeloffset 0 0	')
addMenuItem('	.popupMenu.renderMenu.labelMenu.labelPositionMenu.labelUpperRight	Upper Right	set labeloffset 4 4	')
addMenuItem('	.popupMenu.renderMenu.labelMenu.labelPositionMenu.labelLowerRight	Lower Right	set labeloffset 4 -4	')
addMenuItem('	.popupMenu.renderMenu.labelMenu.labelPositionMenu.labelUpperLeft	Upper Left	set labeloffset -4 4	')
addMenuItem('	.popupMenu.renderMenu.labelMenu.labelPositionMenu.labelLowerLeft	Lower Left	set labeloffset -4 -4	')
addMenuItem('	----	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.renderMenu.bondMenu.bondNone	Off	wireframe off	')
addMenuItem('	.popupMenu.renderMenu.bondMenu.bondWireframe	On	wireframe on	')
addMenuItem('	.popupMenu.renderMenu.bondMenu.-	-		')
addMenuItem('	.popupMenu.renderMenu.bondMenu.bond100	0.10 Å	wireframe .1	')
addMenuItem('	.popupMenu.renderMenu.bondMenu.bond150	0.15 Å	wireframe .15	')
addMenuItem('	.popupMenu.renderMenu.bondMenu.bond200	0.20 Å	wireframe .2	')
addMenuItem('	.popupMenu.renderMenu.bondMenu.bond250	0.25 Å	wireframe .25	')
addMenuItem('	.popupMenu.renderMenu.bondMenu.bond300	0.30 Å	wireframe .3	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.renderMenu.hbondMenu.PDBhbondCalc	Calculate	hbonds calculate	')
addMenuItem('	.popupMenu.renderMenu.hbondMenu.hbondNone	Off	hbonds off	')
addMenuItem('	.popupMenu.renderMenu.hbondMenu.hbondWireframe	On	hbonds on	')
addMenuItem('	.popupMenu.renderMenu.hbondMenu.-	-		')
addMenuItem('	.popupMenu.renderMenu.hbondMenu.PDBhbondSidechain	Set H-Bonds Side Chain	set hbonds sidechain	')
addMenuItem('	.popupMenu.renderMenu.hbondMenu.PDBhbondBackbone	Set H-Bonds Backbone	set hbonds backbone	')
addMenuItem('	.popupMenu.renderMenu.hbondMenu.-	-		')
addMenuItem('	.popupMenu.renderMenu.hbondMenu.hbond100	0.10 Å	hbonds .1	')
addMenuItem('	.popupMenu.renderMenu.hbondMenu.hbond150	0.15 Å	hbonds .15	')
addMenuItem('	.popupMenu.renderMenu.hbondMenu.hbond200	0.20 Å	hbonds .2	')
addMenuItem('	.popupMenu.renderMenu.hbondMenu.hbond250	0.25 Å	hbonds .25	')
addMenuItem('	.popupMenu.renderMenu.hbondMenu.hbond300	0.30 Å	hbonds .3	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.renderMenu.ssbondMenu.ssbondNone	Off	ssbonds off	')
addMenuItem('	.popupMenu.renderMenu.ssbondMenu.ssbondWireframe	On	ssbonds on	')
addMenuItem('	.popupMenu.renderMenu.ssbondMenu.-	-		')
addMenuItem('	.popupMenu.renderMenu.ssbondMenu.PDBssbondSidechain	Set SS-Bonds Side Chain	set ssbonds sidechain	')
addMenuItem('	.popupMenu.renderMenu.ssbondMenu.PDBssbondBackbone	Set SS-Bonds Backbone	set ssbonds backbone	')
addMenuItem('	.popupMenu.renderMenu.ssbondMenu.-	-		')
addMenuItem('	.popupMenu.renderMenu.ssbondMenu.ssbond100	0.10 Å	ssbonds .1	')
addMenuItem('	.popupMenu.renderMenu.ssbondMenu.ssbond150	0.15 Å	ssbonds .15	')
addMenuItem('	.popupMenu.renderMenu.ssbondMenu.ssbond200	0.20 Å	ssbonds .2	')
addMenuItem('	.popupMenu.renderMenu.ssbondMenu.ssbond250	0.25 Å	ssbonds .25	')
addMenuItem('	.popupMenu.renderMenu.ssbondMenu.ssbond300	0.30 Å	ssbonds .3	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.renderMenu.-	-		')
addMenuItem('	.popupMenu.renderMenu.PDBstructureMenu.structureNone	Off	backbone off;cartoons off;ribbons off;rockets off;strands off;trace off;	')
addMenuItem('	.popupMenu.renderMenu.PDBstructureMenu.-	-		')
addMenuItem('	.popupMenu.renderMenu.PDBstructureMenu.backbone	Backbone	backbone 0.3	')
addMenuItem('	.popupMenu.renderMenu.PDBstructureMenu.cartoon	Cartoon	set cartoonRockets false;cartoons on	')
addMenuItem('	.popupMenu.renderMenu.PDBstructureMenu.cartoonRockets	Cartoon Rockets	set cartoonRockets;cartoons on	')
addMenuItem('	.popupMenu.renderMenu.PDBstructureMenu.ribbons	Ribbons	ribbons on	')
addMenuItem('	.popupMenu.renderMenu.PDBstructureMenu.rockets	Rockets	rockets on	')
addMenuItem('	.popupMenu.renderMenu.PDBstructureMenu.strands	Strands	strands on	')
addMenuItem('	.popupMenu.renderMenu.PDBstructureMenu.trace	Trace	trace 0.3	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.renderMenu._AxesMenu.off	Hide	Axes off	')
addMenuItem('	.popupMenu.renderMenu._AxesMenu.dotted	Dotted	Axes dotted	')
addMenuItem('	.popupMenu.renderMenu._AxesMenu.-	-		')
addMenuItem('	.popupMenu.renderMenu._AxesMenu.byPixelMenu.1p	1 px	Axes on	')
addMenuItem('	.popupMenu.renderMenu._AxesMenu.byPixelMenu.3p	3 px	Axes 3	')
addMenuItem('	.popupMenu.renderMenu._AxesMenu.byPixelMenu.5p	5 px	Axes 5	')
addMenuItem('	.popupMenu.renderMenu._AxesMenu.byPixelMenu.10p	10 px	Axes 10	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.renderMenu._AxesMenu.byAngstromMenu.10a	0.10 Å	Axes 0.1	')
addMenuItem('	.popupMenu.renderMenu._AxesMenu.byAngstromMenu.20a	0.20 Å	Axes 0.20	')
addMenuItem('	.popupMenu.renderMenu._AxesMenu.byAngstromMenu.25a	0.25 Å	Axes 0.25	')
addMenuItem('	.popupMenu.renderMenu._AxesMenu.byAngstromMenu.50a	0.50 Å	Axes 0.50	')
addMenuItem('	.popupMenu.renderMenu._AxesMenu.byAngstromMenu.100a	1.0 Å	Axes 1.0	')
addMenuItem('	----	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.renderMenu._BoundBoxMenu.off	Hide	BoundBox off	')
addMenuItem('	.popupMenu.renderMenu._BoundBoxMenu.dotted	Dotted	BoundBox dotted	')
addMenuItem('	.popupMenu.renderMenu._BoundBoxMenu.-	-		')
addMenuItem('	.popupMenu.renderMenu._BoundBoxMenu.byPixelMenu.1p	1 px	BoundBox on	')
addMenuItem('	.popupMenu.renderMenu._BoundBoxMenu.byPixelMenu.3p	3 px	BoundBox 3	')
addMenuItem('	.popupMenu.renderMenu._BoundBoxMenu.byPixelMenu.5p	5 px	BoundBox 5	')
addMenuItem('	.popupMenu.renderMenu._BoundBoxMenu.byPixelMenu.10p	10 px	BoundBox 10	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.renderMenu._BoundBoxMenu.byAngstromMenu.10a	0.10 Å	BoundBox 0.1	')
addMenuItem('	.popupMenu.renderMenu._BoundBoxMenu.byAngstromMenu.20a	0.20 Å	BoundBox 0.20	')
addMenuItem('	.popupMenu.renderMenu._BoundBoxMenu.byAngstromMenu.25a	0.25 Å	BoundBox 0.25	')
addMenuItem('	.popupMenu.renderMenu._BoundBoxMenu.byAngstromMenu.50a	0.50 Å	BoundBox 0.50	')
addMenuItem('	.popupMenu.renderMenu._BoundBoxMenu.byAngstromMenu.100a	1.0 Å	BoundBox 1.0	')
addMenuItem('	----	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.renderMenu._UnitCellMenu.off	Hide	UnitCell off	')
addMenuItem('	.popupMenu.renderMenu._UnitCellMenu.dotted	Dotted	UnitCell dotted	')
addMenuItem('	.popupMenu.renderMenu._UnitCellMenu.-	-		')
addMenuItem('	.popupMenu.renderMenu._UnitCellMenu.byPixelMenu.1p	1 px	UnitCell on	')
addMenuItem('	.popupMenu.renderMenu._UnitCellMenu.byPixelMenu.3p	3 px	UnitCell 3	')
addMenuItem('	.popupMenu.renderMenu._UnitCellMenu.byPixelMenu.5p	5 px	UnitCell 5	')
addMenuItem('	.popupMenu.renderMenu._UnitCellMenu.byPixelMenu.10p	10 px	UnitCell 10	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.renderMenu._UnitCellMenu.byAngstromMenu.10a	0.10 Å	UnitCell 0.1	')
addMenuItem('	.popupMenu.renderMenu._UnitCellMenu.byAngstromMenu.20a	0.20 Å	UnitCell 0.20	')
addMenuItem('	.popupMenu.renderMenu._UnitCellMenu.byAngstromMenu.25a	0.25 Å	UnitCell 0.25	')
addMenuItem('	.popupMenu.renderMenu._UnitCellMenu.byAngstromMenu.50a	0.50 Å	UnitCell 0.50	')
addMenuItem('	.popupMenu.renderMenu._UnitCellMenu.byAngstromMenu.100a	1.0 Å	UnitCell 1.0	')
addMenuItem('	----	')
addMenuItem('	----	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.surfaceMenu.surfDots	Dot Surface	select *;dots on	')
addMenuItem('	.popupMenu.surfaceMenu.surfVDW	van der Waals Surface	isosurface delete resolution 0 solvent 0 translucent	')
addMenuItem('	.popupMenu.surfaceMenu.surfSolventAccessible14	Solvent-Accessible Surface (VDW + 1.4 Angstrom)	isosurface delete resolution 0 sasurface 1.4 translucent	')
addMenuItem('	.popupMenu.surfaceMenu.surfSolvent14	Solvent Surface (1.4-Angstrom probe)	isosurface delete resolution 0 solvent 1.4 translucent	')
addMenuItem('	.popupMenu.surfaceMenu.surfMolecular	Molecular Surface	isosurface delete resolution 0 molecular translucent	')
addMenuItem('	.popupMenu.surfaceMenu.surfMEP	Molecular Electrostatic Potential	isosurface delete resolution 0 molecular map MEP translucent	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.surfaceMenu.-	-		')
addMenuItem('	.popupMenu.surfaceMenu.surfOpaque	Make Opaque	isosurface opaque	')
addMenuItem('	.popupMenu.surfaceMenu.surfTranslucent	Make Translucent	isosurface translucent	')
addMenuItem('	.popupMenu.surfaceMenu.surfOff	Off	isosurface delete;select *;dots off	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.SYMMETRYunitCellMenu.oneUnitCell	{1 1 1}	save orientation;load "" {1 1 1} ;restore orientation	')
addMenuItem('	.popupMenu.SYMMETRYunitCellMenu.fourUnitCells	{2 2 2}	save orientation;load "" {2 2 2} ;restore orientation	')
addMenuItem('	.popupMenu.SYMMETRYunitCellMenu.nineUnitCells	{3 3 3}	save orientation;load "" {3 3 3} ;restore orientation	')
addMenuItem('	.popupMenu.SYMMETRYunitCellMenu.nineUnitCellsRestricted	Polyhedra	save orientation;load "" {3 3 3} ;restore orientation;unitCell {1 1 1}; restrict cell=666; polyhedra 4,6 (visible);center visible;zoom 200	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.-	-		')
addMenuItem('	.popupMenu.zoomMenu.zoom50	50%	zoom 50	')
addMenuItem('	.popupMenu.zoomMenu.zoom100	100%	zoom 100	')
addMenuItem('	.popupMenu.zoomMenu.zoom150	150%	zoom 150	')
addMenuItem('	.popupMenu.zoomMenu.zoom200	200%	zoom 200	')
addMenuItem('	.popupMenu.zoomMenu.zoom400	400%	zoom 400	')
addMenuItem('	.popupMenu.zoomMenu.zoom800	800%	zoom 800	')
addMenuItem('	.popupMenu.zoomMenu.-	-		')
addMenuItem('	.popupMenu.zoomMenu.zoomIn	Zoom In	move 0 0 0 40 0 0 0 0 1	')
addMenuItem('	.popupMenu.zoomMenu.zoomOut	Zoom Out	move 0 0 0 -40 0 0 0 0 1	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.spinMenu.spinOn	On	spin on	')
addMenuItem('	.popupMenu.spinMenu.spinOff	Off	spin off	')
addMenuItem('	.popupMenu.spinMenu.-	-		')
addMenuItem('	.popupMenu.spinMenu.setSpinXMenu.s0	0	set spin X 0	')
addMenuItem('	.popupMenu.spinMenu.setSpinXMenu.s5	5	set spin X 5	')
addMenuItem('	.popupMenu.spinMenu.setSpinXMenu.s10	10	set spin X 10	')
addMenuItem('	.popupMenu.spinMenu.setSpinXMenu.s20	20	set spin X 20	')
addMenuItem('	.popupMenu.spinMenu.setSpinXMenu.s30	30	set spin X 30	')
addMenuItem('	.popupMenu.spinMenu.setSpinXMenu.s40	40	set spin X 40	')
addMenuItem('	.popupMenu.spinMenu.setSpinXMenu.s50	50	set spin X 50	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.spinMenu.setSpinYMenu.s0	0	set spin Y 0	')
addMenuItem('	.popupMenu.spinMenu.setSpinYMenu.s5	5	set spin Y 5	')
addMenuItem('	.popupMenu.spinMenu.setSpinYMenu.s10	10	set spin Y 10	')
addMenuItem('	.popupMenu.spinMenu.setSpinYMenu.s20	20	set spin Y 20	')
addMenuItem('	.popupMenu.spinMenu.setSpinYMenu.s30	30	set spin Y 30	')
addMenuItem('	.popupMenu.spinMenu.setSpinYMenu.s40	40	set spin Y 40	')
addMenuItem('	.popupMenu.spinMenu.setSpinYMenu.s50	50	set spin Y 50	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.spinMenu.setSpinZMenu.s0	0	set spin Z 0	')
addMenuItem('	.popupMenu.spinMenu.setSpinZMenu.s5	5	set spin Z 5	')
addMenuItem('	.popupMenu.spinMenu.setSpinZMenu.s10	10	set spin Z 10	')
addMenuItem('	.popupMenu.spinMenu.setSpinZMenu.s20	20	set spin Z 20	')
addMenuItem('	.popupMenu.spinMenu.setSpinZMenu.s30	30	set spin Z 30	')
addMenuItem('	.popupMenu.spinMenu.setSpinZMenu.s40	40	set spin Z 40	')
addMenuItem('	.popupMenu.spinMenu.setSpinZMenu.s50	50	set spin Z 50	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.spinMenu.-	-		')
addMenuItem('	.popupMenu.spinMenu.setSpinFpsMenu.s0	0	set spin Fps 0	')
addMenuItem('	.popupMenu.spinMenu.setSpinFpsMenu.s5	5	set spin Fps 5	')
addMenuItem('	.popupMenu.spinMenu.setSpinFpsMenu.s10	10	set spin Fps 10	')
addMenuItem('	.popupMenu.spinMenu.setSpinFpsMenu.s20	20	set spin Fps 20	')
addMenuItem('	.popupMenu.spinMenu.setSpinFpsMenu.s30	30	set spin Fps 30	')
addMenuItem('	.popupMenu.spinMenu.setSpinFpsMenu.s40	40	set spin Fps 40	')
addMenuItem('	.popupMenu.spinMenu.setSpinFpsMenu.s50	50	set spin Fps 50	')
addMenuItem('	----	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.VIBRATIONMenu.vibrationOff	Off	vibration off	')
addMenuItem('	.popupMenu.VIBRATIONMenu.vibrationOn	On	vibration on	')
addMenuItem('	.popupMenu.VIBRATIONMenu.vectorMenu.vectorOff	Off	vectors off	')
addMenuItem('	.popupMenu.VIBRATIONMenu.vectorMenu.vectorOn	On	vectors on	')
addMenuItem('	.popupMenu.VIBRATIONMenu.vectorMenu.vector3	3 pixels	vectors 3	')
addMenuItem('	.popupMenu.VIBRATIONMenu.vectorMenu.vector005	0.05 Å	vectors 0.05	')
addMenuItem('	.popupMenu.VIBRATIONMenu.vectorMenu.vector01	0.10 Å	vectors 0.1	')
addMenuItem('	.popupMenu.VIBRATIONMenu.vectorMenu.-	-		')
addMenuItem('	.popupMenu.VIBRATIONMenu.vectorMenu.vectorScale02	Scale 0.2	vector scale 0.2	')
addMenuItem('	.popupMenu.VIBRATIONMenu.vectorMenu.vectorScale05	Scale 0.5	vector scale 0.5	')
addMenuItem('	.popupMenu.VIBRATIONMenu.vectorMenu.vectorScale1	Scale 1	vector scale 1	')
addMenuItem('	.popupMenu.VIBRATIONMenu.vectorMenu.vectorScale2	Scale 2	vector scale 2	')
addMenuItem('	.popupMenu.VIBRATIONMenu.vectorMenu.vectorScale5	Scale 5	vector scale 5	')
addMenuItem('	----	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.FRAMESanimateMenu.animModeMenu.OnceThrough	Play Once	set anim mode once	')
addMenuItem('	.popupMenu.FRAMESanimateMenu.animModeMenu.Palindrome	Palindrome	set anim mode palindrome	')
addMenuItem('	.popupMenu.FRAMESanimateMenu.animModeMenu.Loop	Loop	set anim mode loop	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.FRAMESanimateMenu.-	-		')
addMenuItem('	.popupMenu.FRAMESanimateMenu.play	Play	anim on	')
addMenuItem('	.popupMenu.FRAMESanimateMenu.stop	Stop	anim off	')
addMenuItem('	.popupMenu.FRAMESanimateMenu.nextframe	Next Frame	frame next	')
addMenuItem('	.popupMenu.FRAMESanimateMenu.prevframe	Previous Frame	frame prev	')
addMenuItem('	.popupMenu.FRAMESanimateMenu.rewind	Rewind	frame 1	')
addMenuItem('	.popupMenu.FRAMESanimateMenu.-	-		')
addMenuItem('	.popupMenu.FRAMESanimateMenu.animFpsMenu.animfps5	5	set anim fps 5	')
addMenuItem('	.popupMenu.FRAMESanimateMenu.animFpsMenu.animfps10	10	set anim fps 10	')
addMenuItem('	.popupMenu.FRAMESanimateMenu.animFpsMenu.animfps20	20	set anim fps 20	')
addMenuItem('	.popupMenu.FRAMESanimateMenu.animFpsMenu.animfps30	30	set anim fps 30	')
addMenuItem('	.popupMenu.FRAMESanimateMenu.animFpsMenu.animfps50	50	set anim fps 50	')
addMenuItem('	----	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.-	-		')
addMenuItem('	.popupMenu.measureMenu.showMeasurementsCheckbox	Show Measurements	set showMeasurements [true|false]	')
addMenuItem('	.popupMenu.measureMenu.-	-		')
addMenuItem('	.popupMenu.measureMenu.measureOff	Double-Click begins and ends all measurements	set pickingstyle MEASURE OFF; set picking OFF	')
addMenuItem('	.popupMenu.measureMenu.measureDistance	Click for distance measurement	set pickingstyle MEASURE; set picking MEASURE DISTANCE	')
addMenuItem('	.popupMenu.measureMenu.measureAngle	Click for angle measurement	set pickingstyle MEASURE; set picking MEASURE ANGLE	')
addMenuItem('	.popupMenu.measureMenu.measureTorsion	Click for torsion (dihedral) measurement	set pickingstyle MEASURE; set picking MEASURE TORSION	')
addMenuItem('	.popupMenu.measureMenu.-	-		')
addMenuItem('	.popupMenu.measureMenu.measureDelete	Delete measurements	measure delete	')
addMenuItem('	.popupMenu.measureMenu.measureList	List measurements	console on;show measurements	')
addMenuItem('	.popupMenu.measureMenu.-	-		')
addMenuItem('	.popupMenu.measureMenu.distanceNanometers	Distance units nanometers	select *; set measure nanometers	')
addMenuItem('	.popupMenu.measureMenu.distanceAngstroms	Distance units Angstroms	select *; set measure angstroms	')
addMenuItem('	.popupMenu.measureMenu.distancePicometers	Distance units picometers	select *; set measure picometers	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.pickingMenu.pickOff	Off	set picking off	')
addMenuItem('	.popupMenu.pickingMenu.pickCenter	Center	set picking center	')
addMenuItem('	.popupMenu.pickingMenu.pickLabel	Label	set picking label	')
addMenuItem('	.popupMenu.pickingMenu.pickAtom	Select atom	set picking atom	')
addMenuItem('	.popupMenu.pickingMenu.pickChain	Select chain	set picking chain	')
addMenuItem('	.popupMenu.pickingMenu.pickElement	Select element	set picking element	')
addMenuItem('	.popupMenu.pickingMenu.pickGroup	Select group	set picking group	')
addMenuItem('	.popupMenu.pickingMenu.pickMolecule	Select molecule	set picking molecule	')
addMenuItem('	.popupMenu.pickingMenu.pickSite	Select site	set picking site	')
addMenuItem('	.popupMenu.pickingMenu.pickSpin	Spin	set picking spin	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.-	-		')
addMenuItem('	.popupMenu.showConsole	Console	console	')
addMenuItem('	.popupMenu.showMenu.showHistory	History	console on;show history	')
addMenuItem('	.popupMenu.showMenu.showFile	File Contents	console on;show file	')
addMenuItem('	.popupMenu.showMenu.showFileHeader	File Header	console on;getProperty FileHeader	')
addMenuItem('	.popupMenu.showMenu.-	-		')
addMenuItem('	.popupMenu.showMenu.showOrient	Orientation	console on;show orientation	')
addMenuItem('	.popupMenu.showMenu.showMeasure	Measure	console on;show measure	')
addMenuItem('	.popupMenu.showMenu.-	-		')
addMenuItem('	.popupMenu.showMenu.showSpacegroup	Space group	console on;show spacegroup	')
addMenuItem('	.popupMenu.showMenu.SYMMETRYshowSymmetry	Symmetry	console on;show symmetry	')
addMenuItem('	.popupMenu.showMenu.showUnitCell	Unit cell	console on;show unitcell	')
addMenuItem('	.popupMenu.showMenu.-	-		')
addMenuItem('	.popupMenu.showMenu.showIsosurface	Isosurface JVXL data	console on;show isosurface	')
addMenuItem('	.popupMenu.showMenu.showMo	Molecular orbital JVXL data	console on;show mo	')
addMenuItem('	.popupMenu.showMenu.-	-		')
addMenuItem('	.popupMenu.showMenu.extractMOL	Extract MOL data	console on;getproperty extractModel "visible" 	')
addMenuItem('	----	')
addMenuItem('	.popupMenu.-	-		')
addMenuItem('	.popupMenu.aboutMenu.jmolUrl	www.jmol.org	show url "http://www.jmol.org"	')
addMenuItem('	.popupMenu.aboutMenu.mouseManualUrl	Mouse Manual	show url "http://wiki.jmol.org/index.php/Mouse_Manual"	')
addMenuItem('	.popupMenu.aboutMenu.translatingUrl	Translations	show url "http://wiki.jmol.org/index.php/Internationalisation"	')
addMenuItem('	----	')
